prefix : <http://new/gist/stuff/>
prefix gist: <https://ontologies.semanticarts.com/gist/>
prefix owl:  <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd:  <http://www.w3.org/2001/XMLSchema#> 

Select distinct ?observationsURI ?sensor ?UoMLbl  ?mindv  ?maxdv  ?countdv  ?earliest  ?latest
{

?observationsURI a :ObservationSummary ;
   :recorded_by ?sensor ;
    :period_minimum ?mindv ;
	:period_maximum ?maxdv ;
    :period_number_observations ?countdv ;
    :period_earliest_observation_time ?earliest ;
    :period_latest_observation_time ?latest ;
    gist:hasUoM ?UoM ;
    . 
  ?UoM skos:prefLabel ?UoMLbl .
}

order by ?observationsURI ?sensor ?UoM